# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "forest"
defaultAppearance = "dark"  # valid options: light or dark
autoSwitchAppearance = true

enableA11y = false
enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = false

replyByEmail = false

mainSections = ["blog", "writeups", "achievements", "projects"]
# robots = ""

disableImageOptimization = true
disableImageOptimizationMD = true
disableTextInHeader = false
# backgroundImageWidth = 1200

defaultBackgroundImage = "img/background.gif" # used as default for background images
# defaultFeaturedImage = "IMAGE.jpg" # used as default for featured images in all articles
# defaultSocialImage = "/android-chrome-512x512.png" # used as default for social media sharing (Open Graph and Twitter)
hotlinkFeatureImage = false
# imagePosition = "50% 50%"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

fingerprintAlgorithm = "sha512" # Valid values are "sha512" (default), "sha384", "sha256"

giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v11.next.forgejo.org"

[header]
layout = "fixed-fill-blur" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = false
showScrollToTop = true

[homepage]
layout = "background"                # valid options: page, profile, hero, card, background, custom
homepageImage = "img/background.gif" # used in: hero, and card
showRecent = true
showRecentItems = 6
showMoreLink = true
showMoreLinkDest = "/writeups/"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true          # only used when layout equals background
disableHeroImageFilter = false       # only used when layout equals hero

[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = true
# showAuthorBottom = false
showHero = true
heroStyle = "background"           # valid options: basic, big, background, thumbAndBackground
layoutBackgroundBlur = true        # only used when heroStyle equals background or thumbAndBackground
layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
# editURL = "https://github.com/username/repo/"
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showRelatedContent = true
relatedContentLimit = 3
showTaxonomies = true                                                 # use showTaxonomies OR showCategoryOnly, not both
showCategoryOnly = false                                              # use showTaxonomies OR showCategoryOnly, not both
showAuthorsBadges = false
showWordCount = true
sharingLinks = ["linkedin", "twitter", "reddit", "facebook", "email"]
showZenMode = true

[list]
showHero = true
heroStyle = "background"           # valid options: basic, big, background, thumbAndBackground
layoutBackgroundBlur = true        # only used when heroStyle equals background or thumbAndBackground
layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
showBreadcrumbs = true
showSummary = false
showViews = false
showLikes = false
showTableOfContents = true
showCards = true
orderByWeight = false
groupByYear = true
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = ["taxonomy", "term"]

[taxonomy]
showTermCount = true
showHero = true
heroStyle = "Background"   # valid options: basic, big, background, thumbAndBackground
showBreadcrumbs = true
showViews = false
showLikes = false
showTableOfContents = true
cardView = true

[term]
showHero = true
heroStyle = "background"    # valid options: basic, big, background, thumbAndBackground
showBreadcrumbs = true
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = true
cardViewScreenWidth = false

[firebase]
# apiKey = "XXXXXX"
# authDomain = "XXXXXX"
# projectId = "XXXXXX"
# storageBucket = "XXXXXX"
# messagingSenderId = "XXXXXX"
# appId = "XXXXXX"
# measurementId = "XXXXXX"

[fathomAnalytics]
# site = "ABC12345"
# domain = "llama.yoursite.com"

[umamiAnalytics]
# websiteid = "ABC12345"
# domain = "llama.yoursite.com"
# dataDomains = "yoursite.com,yoursite2.com"
# scriptName = ""
# enableTrackEvent = true

[selineAnalytics]
# token = "XXXXXX"
# enableTrackEvent = true

[buymeacoffee]
# identifier = ""
# globalWidget = true
# globalWidgetMessage = "Hello"
# globalWidgetColor = "#FFDD00"
# globalWidgetPosition = "right"

[verification]
# google = ""
# bing = ""
# pinterest = ""
# yandex = ""
# fediverse = ""

[rssnext]
# feedId = ""
# userId = ""

[advertisement]
# adsense = ""
